-- Conference module main table
CREATE TABLE IF NOT EXISTS module_conferences (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  user_id INT(11),
  user_updated INT(11),
  date_created DATETIME DEFAULT CURRENT_TIMESTAMP,
  date_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  memo TEXT DEFAULT NULL,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(100) DEFAULT NULL,
  topic VARCHAR(255) DEFAULT NULL,
  mode VARCHAR(50) DEFAULT NULL,
  venue VARCHAR(255) DEFAULT NULL,
  schedule DATETIME DEFAULT NULL,
  description TEXT DEFAULT NULL,
  organizers TEXT DEFAULT NULL,
  sponsors TEXT DEFAULT NULL,
  images TEXT DEFAULT NULL,
  tags TEXT DEFAULT NULL,
  ticket_options TEXT DEFAULT NULL,
  custom_fields TEXT DEFAULT NULL,
  privacy TINYINT(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
